version: '3'
services:
  #Nginx Service
  web:
    image: nginx:alpine
    container_name: web
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes: 
      - ./:/var/www
      - .docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
  #PHP
  backend:
    build: 
      context: .
      dockerfile: .docker/php/Dockerfile
    image: php:7.4-fpm
    container_name: backend
    restart: unless-stopped
    tty: true
    environment: 
      SERVICES_NAME: backend
      SERVICES_TAGS: dev
    working_dir: /var/www
    volumes: 
      - ./:/var/www
      - .docker/php/local.ini:/usr/local/php/conf.d/local.ini
    networks: 
      - app-network
  #Mysql Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: test_123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - db-data:/var/lib/mysql/
      - .docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network
#Docker network
networks: 
  app-network:
    driver: bridge
#Volumes
volumes: 
  db-data:
    driver: local